"""MRI-NUFFT

MRI-NUFFT provides a easy to use fourier operator for non cartesian
reconstruction.

Doing Non Cartesian MR Imaging has never been so easier.
"""

from .operators import (
    MRICufiNUFFT,
    MRITensorflowNUFFT,
    MRIFourierCorrected,
    MRIfinufft,
    get_operator,
    check_backend,
)

__all__ = [
    "get_operator",
    "check_backend",
    "MRICufiNUFFT",
    "MRITensorflowNUFFT",
    "MRIFourierCorrected",
    "MRIfinufft",
]


try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import version as __version__
except ImportError:
    # -- Source mode --
    # use setuptools_scm to get the current version from src using git
    from setuptools_scm import get_version as _gv
    from os import path as _path

    __version__ = _gv(_path.join(_path.dirname(__file__), _path.pardir))
